### ISSUE TITLE
Adapt scaling when running on Java 9

### ISSUE THREAD

**Issue by lukeu** [lukeu/swing-dpi#1]
Task: detect usage of Java 9 to avoid "over scaling", since they of course do this also

 This will allow:
 * applications running on Java <= 8 to be tested on JDK 9 EA builds.
 * swing-dpi to continue to provide UI-scaling as a user-preference in a Java-independent and L&F independent manner (it will continue to be useful for this after Java-9 is released too)

Just as a comment: JDK 9 has come along in leaps and bounds since I first tested their HiDPI support. It is now perfectly usable, and of course much superior to swing-dpi's approach because there are many things we simply cannot do from outside the JDK, or which would take far too much effort. Can't wait for the official release! (also: compact strings)

**Comment by thhart** [comment]
Hello, I am maintaining some Swing applications especially in Linux and unfortunately the scaling support even in JDK 9 is not working with Metal L&F. I can see only GTK is working well.

**Comment by lukeu** [comment]
Oh? That's interesting. Yes it's possible that this helper utility might be useful for you then.

It is not entirely magic as there's only so much that can be done from outside the JDK. It just tries to do as much as it can via tweaking the UIManager, ironing out the idiosyncrasies between the various L&Fs. In addition it requires a few _invasive_ tweaks into your code:

 - you have to call a wrapper function around any hard-coded layout dimensions
 - you have to scale icons (e.g. using the `ScaledIcon` helper class provided)
 - poor support for scaling HTML. (works so long as the HTML doesn't try to apply style-sheets)

Having said that, we've managed to apply it to a fairly complex IDE-like application with good success and without too much effort. Most of our dialogs & views use preferred layouts, which don't need manual tweaking.

Plans here have pretty much been on hold since there hasn't been any external interest to date and my current projects will stick on JDK-8 for a while longer. However if this still sounds useful to you, I'd be happy to dive back in and finish off a few 'todo' items - detecting JDK-9 being the most important one. 

e.g. based from your information, I could add a rule to continue to implement JDK-8 - style scaling on non-GTK Linux even on JDK-9.

Could you let me know what Linux distro(s) / Window Manager(s) you need to support, and what sort of Swing controls your application uses?

**Comment by lukeu** [comment]
This was solved in release 0.8  (git-sha: 79fb5bffacf2)

Then in release 0.9, swing-dpi was also taught to turn its scaling back on again when the JDK's scaling is disabled:

    -Dsun.java2d.uiScale.enabled=false

This has proven useful in some Linux environments, where the user just wants to configure some scaling preference in each application itself rather than mess around with complicated X-windows settings.

(I see that Intellij [does something very similar](https://intellij-support.jetbrains.com/hc/en-us/articles/360007994999-HiDPI-configuration).)

Anyway, I think this is enough to declare this closed.

BTW if you're in the position to include a heavier dependency, I can: 
 * Highly recommend the [Flat LaF](https://github.com/JFormDesigner/FlatLaf) as an excellent, clean cross-platform LaF
 * Or if you want more functionality and widgets, there's also [Radiance](https://github.com/kirill-grouchnikov/radiance)

These both deal with HiDPI scaling nicely, internally without a "hack it from the outside" library like this one, which targets the JDK's built-in (and unloved) L&Fs.
